### ISSUE TITLE
Minimum required version of flex? (was Conda build/install error mentioning flex / region-4.8)

### ISSUE THREAD

**Issue by joleroi** [sherpa/sherpa#146] opened 2016-01-15 11:03 UTC
I am trying to install the sherpa head version on Ubuntu 14.04. 
I am using Python 2.7 within an Anaconda environment.

The installation fails with the following error message
```
checking lex output file root... configure: error: cannot find output from flex; giving up
configure: error: ./configure failed for region-4.8
```

Does anyone have an idea what I could try to solve this problem? The full build/install log is here
https://gist.github.com/joleroi/17026456732d568b2ce5

**Comment by DougBurke** [comment] 2016-01-15 13:54
It works for me on ubuntu 15.10 with flex version 2.5.39. Strange.

You could try going back to before PR #137 was merged - e.g. changeset d83e6eec0b75d5613a13de63dd37795558a7726d - and see if you can build that (this would indicate if its a problem with the new region library code we added, and would hopefully get you a working sherpa installation).

**Comment by joleroi** [comment] 2016-01-15 14:19
Going back to the older version of the code did not help.

Nevertheless, you solved my problem. I was using flex 4.3 (installed via pip). I removed the package and installed flex 2.5.39 via aptitude. Thanks a lot!

**Comment by DougBurke** [comment] 2016-01-15 14:51
Thanks. @olaurino do we know if the region code has a minimum requirement on flex? If so, we should document it.

**Comment by olaurino** [comment] 2016-01-19 15:08
Before forwarding this issue to the region library maintainers, I would like to make sure I understand the issue.

I found this package on PyPI:
https://pypi.python.org/pypi/flex

This does not look like the `flex` executable that the region library needs in order to be installed, which is this:
http://flex.sourceforge.net/

So, I think configure was being confused by the existence of a `flex` executable that, however, was not the correct tool.

@joleroi do you think this is a reasonable explanation for the issue you were experiencing?

**Comment by DougBurke** [comment] 2016-01-19 15:10
That is an *unfortunate* choice of name for that package!

**Comment by cdeil** [comment] 2016-01-19 15:23
Well ... even if it's not the cause of the issue here, it would be good if that name were changed.
So I've filed an issue asking politely here: https://github.com/pipermerriam/flex/issues/93

**Comment by pipermerriam** [comment] 2016-01-19 16:13
Sorry for the confusion.  This will be fixed with the next release.

https://github.com/pipermerriam/flex/pull/94

**Closed** 2016-01-19 16:14 UTC
Labels: area:build, note:not-a-bug, type:bug
