### ISSUE TITLE
CentOS 5 compatibility of 4.9.1 conda package

### ISSUE THREAD

**Issue by jeanconn** [sherpa/sherpa#414] opened 2017-12-08 17:00 UTC
Hi,

I'm trying to use the sherpa 4.9.1 linux 64 py36 conda package on a CentOS 5 system, but I'm guessing that you've moved to doing package builds on a different OS/version?  I didn't see that called out in the release notes but:

```
Package plan for installation in environment /data/fido/ska3/arch/x86_64-linux_CentOS-5:

The following NEW packages will be INSTALLED:

    sherpa: 4.9.1-py36_0 sherpa

Proceed ([y]/n)? y

unagi: ipython
Python 3.6.0 |Continuum Analytics, Inc.| (default, Dec 23 2016, 12:22:00) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.1.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import sherpa.ui as ui
...
ImportError: /data/fido/ska3/arch/x86_64-linux_CentOS-5/lib/python3.6/site-packages/sherpa/models/_modelfcts.cpython-36m-x86_64-linux-gnu.so: ELF file OS ABI invalid
```
Is there a chance you could just build these on CentOS5?  It think it only wins you more compatibility, but I don't know if you are dealing with other challenges.

Thanks!

**Comment by olaurino** [comment] 2017-12-08 17:34
Jean,

It should have been listed in the release notes, but it wasn't. Sorry about that.

We moved from centOS5 to centOS6 following the same move in CIAO (the change was listed on the CIAO release notes). Also, it wasn't clear what Anaconda supports, but when I asked they told me not all packages in conda are binary compatible with centOS5 (see https://github.com/ContinuumIO/anaconda-issues/issues/1349#issuecomment-271958619). So we went with CentOS6.

However, I agree that building on CentOS5 is preferable, so I'll suggest to the team we try and go back to CentOS5 unless we hit issues (which is unlikely). We could also release a new 4.9.1 conda package for Linux built on CentOS5.

**Comment by olaurino** [comment] 2017-12-08 17:40
By the way, Continuum does list CentOS6+ in their system requirements:
https://docs.anaconda.com/anaconda/install/#system-requirements

**Comment by jeanconn** [comment] 2017-12-08 19:26
Thanks Omar.  If you see a lightweight way to go back to CentOS5 or to hand off a 64 bit CentOS5 4.9.1 sherpa conda package to me, that would be awesome.  And yes, we've started to see the new Anaconda packages are built on CentOS6.  Luckily we have been slow enough to upgrade packages that this hasn't been a much of a problem yet and hopefully they won't decide to *rebuild* old packages using the new systems/compilers.  

Also, regarding "I asked they told me not all packages in conda are binary compatible with centOS5", I at least have haven't seen anything about any CentOS5-built packages not being forward compatible to CentOS6 machines.

cc @taldcroft @matthewdahmer

**Comment by olaurino** [comment] 2017-12-08 19:31
> Also, regarding "I asked they told me not all packages in conda are binary compatible with centOS5", I at least have haven't seen anything about any CentOS5-built packages not being forward compatible to CentOS6 machines.

Hmm... not sure I understand, maybe my previous statement was ambiguous. As you confirmed, some of their packages are built on CentOS6, so I expect some packages not to run on CentOS5. I think we are on the same page, anyway.

**Comment by olaurino** [comment] 2017-12-08 20:19
@jeanconn would building Sherpa from sources be an option for you? If you have gcc, including a fortran compiler, that should be straightforward (if you don't need xspec, which the conda binary does not provide anyway). As a matter of fact a `pip install git+https://github.com/sherpa/sherpa@4.9.1` should be sufficient.

**Comment by jeanconn** [comment] 2017-12-08 22:13
For me, this looks like it now dies somewhere in trying to make the region library (which is basically all the games I was hoping never to have to play again once we moved to conda)
```
  make[1]: Entering directory `/tmp/pip-mnqj0d1h-build/extern/region-4.9'
    Making install in src
    make[2]: Entering directory `/tmp/pip-mnqj0d1h-build/extern/region-4.9/src'
    test -f regparser.c || /bin/sh ../ylwrap regparser.y y.tab.c regparser.c y.tab.h regparser.h y.output regparser.output -- bison -y  -d -p"regYY"
    test -f reglexer.c || /bin/sh ../ylwrap reglexer.l lex.yy.c reglexer.c -- flex  -o lex.yy.c
    flex: can't open lex.yy.c
    make[2]: *** [reglexer.c] Error 1
    make[2]: *** Waiting for unfinished jobs....
    updating regparser.h
    make[2]: Leaving directory `/tmp/pip-mnqj0d1h-build/extern/region-4.9/src'
    make[1]: *** [install-recursive] Error 1
    make[1]: Leaving directory `/tmp/pip-mnqj0d1h-build/extern/region-4.9'
    make: *** [install-recursive] Error 1
    
    ----------------------------------------
Command "/data/fido/ska3/arch/x86_64-linux_CentOS-5/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-mnqj0d1h-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-b9o4rncb-record/install-record.txt --single-version-externally-managed --compile" failed with error code 2 in /tmp/pip-mnqj0d1h-build/
```

**Comment by taldcroft** [comment] 2017-12-08 23:41
@jeanconn - for the record was this on a CentOS-5 machine?

**Comment by taldcroft** [comment] 2017-12-08 23:42
@olaurino - FYI on the HEAD network the machine `unagi` is CentOS-5 and is our build platform.

**Comment by jeanconn** [comment] 2017-12-08 23:50
Yes, for the record it was on `unagi`.

**Comment by olaurino** [comment] 2017-12-09 05:44
@jeanconn I compared my provisioning script for the VM that I used to build Sherpa on CentOS 5 with your environment on `unagi`. Unless I am missing something in non-standard locations, as far as `gcc` goes you have 4.1.2. While I never tested the build with that compiler (I used to use 4.8 for creating the binaries), it is probably fine. The main problem at this point is `flex`. You have version 2.5.4, but that's too old. In my provisioning script I used to install 2.3.35 with the following line:
```
$ sudo rpm -Uvh ftp://ftp.pbone.net/mirror/pkgs.repoforge.org/flex/flex-2.5.35-0.8.el5.rfb.x86_64.rpm
```
Conda does have a flex package but I tried installing it in one of my folders while on `unagi` and it doesn't run because of binary incompatibility (not build on CentOS 5). [As a matter of fact, I tried installing the latest Miniconda and that failed to run too for the same reason, so I had to fall back on the latest 3.x version.]

Now, I can't claim that if you install `flex` 2.5.35 the build will work, but it should go past the region library issue.

In the meantime I started working on a conda binary package for 4.9.1 built on CentOS5, but since CentOS5 is well past its EOL it looks like `yum update` (which I still had in my provisioning script) doesn't work. After setting the `yum` mirrors manually the provisioning script is now working again, but then `conda build` fails because `python 3.6.3` was not built on CentOS5. I'll try setting it to 3.6.0 (I see in your original report that's the version you use in your conda environment), but that will have to wait until Monday, at this point.

If I manage to get a CentOS5 build I'll upload it to some conda channel so you can grab it, but at this point I don't think it makes sense to use CentOS5 as the baseline build system, given that Continuum itself does not seem to support it anymore for its latest python builds. If you still need binaries for this system, and you can't build from sources, I can try and make sure I can keep building them in a vagrant box. Actually, I should probably take a snapshot of the vagrant box that does not need any provisioning before it's too late.

**Comment by jeanconn** [comment] 2017-12-11 01:56
@olaurino Is your vagrant provisioning script in this repo somewhere?  That also might be useful for me at some point in the future.

**Comment by jeanconn** [comment] 2017-12-11 02:06
Also, regarding: 

> Conda does have a flex package but I tried installing it in one of my folders while on unagi and it doesn't run because of binary incompatibility (not built on CentOS 5

I *think* if I use something like this in my .condarc to not get the "new" conda stuff
```
default_channels:
  - https://repo.continuum.io/pkgs/free
  - https://repo.continuum.io/pkgs/r
  - https://repo.continuum.io/pkgs/msys2
```
I get a flex 2.6.0 that seems to work (at least that flex seemed to work enough to say it let me pip install sherpa 4.9.1).  I'll test more.

**Comment by jeanconn** [comment] 2017-12-11 14:42
Right, with new flex, this pip installs OK but still doesn't run, importing sherpa.ui

```
/data/fido/ska3/arch/x86_64-linux_CentOS-5/lib/python3.6/site-packages/sherpa/fit.py in <module>()
     35 from sherpa.estmethods import Covariance, EstNewMin
     36 from sherpa.models import SimulFitModel
---> 37 from sherpa.optmethods import LevMar, NelderMead
     38 from sherpa.stats import Chi2, Chi2Gehrels, Cash, CStat, Chi2ModVar, \
     39     LeastSq, Likelihood, WStat

/data/fido/ska3/arch/x86_64-linux_CentOS-5/lib/python3.6/site-packages/sherpa/optmethods/__init__.py in <module>()
     23      get_keyword_names, get_keyword_defaults, print_fields
     24 from sherpa.utils.err import FitErr
---> 25 from sherpa.optmethods.optfcts import *
     26 
     27 warning = logging.getLogger(__name__).warning

/data/fido/ska3/arch/x86_64-linux_CentOS-5/lib/python3.6/site-packages/sherpa/optmethods/optfcts.py in <module>()
     27 from six.moves import xrange
     28 
---> 29 from . import _minpack
     30 from . import _minim
     31 from . import _saoopt

ImportError: /data/fido/ska3/arch/x86_64-linux_CentOS-5/lib/python3.6/site-packages/sherpa/optmethods/_minpack.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _gfortran_set_std
```

**Comment by olaurino** [comment] 2017-12-11 14:50
@jeanconn I use `libgcc` and `libgfortran` as conda dependencies in the conda recipe. My workstation had issues waking up this morning, so unfortunately I lost an hour just to make it start properly. I think I can easily provide you with:
  * conda binaries for CentOS 5 (my experiments from Friday night seemed to work with both gcc 4.8.5 and with the native gcc shipped with CentOS 5).
  * A Vagrantfile to build the conda package yourself on a CentOS 5 virtual box.
  * A vagrant box already provisioned with what you need to build the conda package.
  * A Docker container to build the conda package for CentOS 5.

Let me work on it a little bit and I'll give you an update later.

There is a repo with the Vagrantfile, the conda recipes, etc. but it's a different one. I'll give you a pointer to a special branch I have locally to build the conda package for you.

**Comment by DougBurke** [comment] 2017-12-11 14:52
@jeanconn  what does

```
% ldd /data/fido/ska3/arch/x86_64-linux_CentOS-5/lib/python3.6/site-packages/sherpa/optmethods/_minpack.cpython-36m-x86_64-linux-gnu.so
```

return? I'm not sure it'll help, but I'm wondering if - for some reason, which I can't really see how but YMMV - a `-lgfortran` is being missed from the build?

**Comment by olaurino** [comment] 2017-12-11 17:09
@jeanconn I uploaded a conda binary of Sherpa 4.9.1 built on a CentOS 5 docker container. Could you please try installing it with

```
$ conda install -c cxc/channel/dev sherpa=4.9.1
```
I tested this command on `unagi` within my CentOS5-compatible conda environment, and I am currently running all the regression tests (see https://github.com/sherpa/sherpa#testing-sherpa), and everything seems to pass, excluding the tests skipped because of xspec and matplotlib missing.

I retro-fitted my new CentOS 6 docker container for building Sherpa so it would build it on CentOS 5. The container should be able to build a conda package of a future version of Sherpa. I'll point you to instructions after I clean up and cross all the t's. I am not sure whether I should also create and archive a vagrant box capable of doing the same. Do you have preferences between vagrant and docker?

**Comment by olaurino** [comment] 2017-12-12 16:24
@jeanconn while you should be fine with the conda package, I was trying to think of a good reason why you had this issue:

> ImportError: /data/fido/ska3/arch/x86_64-linux_CentOS-5/lib/python3.6/site-packages/sherpa/optmethods/_minpack.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _gfortran_set_std

My guess is that you are using the system compiler (gcc 4.4.7?) for building Sherpa from sources, which links against the `libgcc` and `libgfortran` that come with the compiler. Then in the conda environment you have the `libgfortran` and `libgcc` that come with the environment, which are probably incompatible with the system ones.

So either you force the source build to use the libraries in the conda environment, which is what `conda-build` does, or you remove `libgcc` and `libgfortran` from the conda environment. Of course removing them is only an option if it's only Sherpa that depends on them, which is not necessarily true.

This repository https://github.com/sherpa/legacy-builds/tree/centos5 contains the conda recipes I used to build the package, so you could use `conda-build` yourself rather than `pip install`.

None of this is necessary if the conda package I pointed you to `just works(tm)`, of course.

**Comment by jeanconn** [comment] 2017-12-12 16:41
Hi @olaurino .  Regarding `just works(tm)`, I'm seeing something *really* weird with this.  If I install the sherpa conda package you made into my environment, it doesn't work.  If I uninstall install libgfortan, scipy, and scikit-learn (and broken sherpa), reinstall sherpa (+libgfortran), and then reinstall scipy and scikit-learn, it works (ignoring expected DS9 warning).  I'm losing faith in building, linking, and conda...

```
unagi: conda list | egrep '(libgcc|libgfortran|scipy|sherpa)'
libgcc                    5.2.0                         0    defaults
libgfortran               3.0.0                         1    defaults
scipy                     0.19.1              np113py36_0    defaults

unagi: conda install -c cxc/channel/dev sherpa=4.9.1
Fetching package metadata ...........
Solving package specifications: .

Package plan for installation in environment /tmp/ska3up/arch/x86_64-linux_CentOS-5:

The following NEW packages will be INSTALLED:

    sherpa: 4.9.1-py36he678ed3_0 cxc/channel/dev

The following packages will be DOWNGRADED:

    libgcc: 5.2.0-0              defaults        --> 4.8.5-2 defaults

unagi: python -c "import sherpa.ui"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/ska3up/arch/x86_64-linux_CentOS-5/lib/python3.6/site-packages/sherpa/ui/__init__.py", line 20, in <module>
    import sherpa.all
  File "/tmp/ska3up/arch/x86_64-linux_CentOS-5/lib/python3.6/site-packages/sherpa/all.py", line 37, in <module>
    from sherpa.fit import *
  File "/tmp/ska3up/arch/x86_64-linux_CentOS-5/lib/python3.6/site-packages/sherpa/fit.py", line 37, in <module>
    from sherpa.optmethods import LevMar, NelderMead
  File "/tmp/ska3up/arch/x86_64-linux_CentOS-5/lib/python3.6/site-packages/sherpa/optmethods/__init__.py", line 25, in <module>
    from sherpa.optmethods.optfcts import *
  File "/tmp/ska3up/arch/x86_64-linux_CentOS-5/lib/python3.6/site-packages/sherpa/optmethods/optfcts.py", line 29, in <module>
    from . import _minpack
ImportError: libgfortran.so.3: cannot open shared object file: No such file or directoryunagi: conda remove libgfortran
Fetching package metadata .........
Solving package specifications: .

Package plan for package removal in environment /tmp/ska3up/arch/x86_64-linux_CentOS-5:

The following packages will be REMOVED:

    libgfortran:  3.0.0-1              defaults       
    scikit-learn: 0.19.0-np113py36_0   defaults       
    scipy:        0.19.1-np113py36_0   defaults       
    sherpa:       4.9.1-py36he678ed3_0 cxc/channel/dev

Proceed ([y]/n)? yunagi: conda install -c cxc/channel/dev sherpa=4.9.1 
Fetching package metadata ...........
Solving package specifications: .

Package plan for installation in environment /tmp/ska3up/arch/x86_64-linux_CentOS-5:

The following NEW packages will be INSTALLED:

    libgfortran: 3.0.0-1              defaults       
    sherpa:      4.9.1-py36he678ed3_0 cxc/channel/dev

Proceed ([y]/n)? y

unagi: python -c "import sherpa.ui"
WARNING: imaging routines will not be available, 
failed to import sherpa.image.ds9_backend due to 
'RuntimeErr: DS9Win unusable: Could not find xpaget on your PATH'unagi: conda install scipy scikit-learn
Fetching package metadata .........
Solving package specifications: .

Package plan for installation in environment /tmp/ska3up/arch/x86_64-linux_CentOS-5:

The following NEW packages will be INSTALLED:

    scikit-learn: 0.19.0-np113py36_0 defaults
    scipy:        0.19.1-np113py36_0 defaults

Proceed ([y]/n)? y

unagi: python -c "import sherpa.ui"
WARNING: imaging routines will not be available, 
failed to import sherpa.image.ds9_backend due to 
'RuntimeErr: DS9Win unusable: Could not find xpaget on your PATH'
```

**Comment by olaurino** [comment] 2017-12-12 16:49
The first time you install `sherpa` it downgrades `libgcc` from 5.2 to 4.8... that's kind of dangerous, and it might explain the issues you got afterwards. My concern is that you have a rather specific set of dependencies and if you downgrade some of them then sherpa works, but maybe something else is broken.

Indeed the best option in your case might be to tweak the conda recipe to include the dependencies in your environment (e.g. `libgcc` 5) and then use `conda-build` to build it yourself.

I could also do it for you, but in order for the test to be meaningful I'd need a dump of your environment so I can reproduce it independently. I tried doing it on Friday, but I am not sure I understand your directory structure, and `conda export` (or whatever the command is) refused to work because of an issue with the environment name.

**Comment by olaurino** [comment] 2017-12-12 17:05
I have a possible explanation for the weirdness you experienced. Some `libgcc` conda packages contain `libgfortran.so.3` while other don't. See for instance: https://github.com/ContinuumIO/anaconda-issues/issues/686#issuecomment-248117602

My educated guess is that `libgcc` 5.2.0 contains `libgfortran.so.3`, so when it was downgraded to `libgcc` 4.8.5 (which doesn't have it) it removed it, ignoring that you also had `libgfortran` 3.0.0. When you uninstalled installed `libgfortran` 3.0.0 the library was installed again, and everything could work.

You need to ask yourself if you really needed `libgcc` 5.2.0 and which packages in your environment depend on it. If you can do without it that you might be safe. Otherwise you could rebuild the Sherpa conda package with 5.2.0 rather than `libgcc` 4.8.3 **and** `libgfortran` 3.0.0.

Does that make sense?

**Comment by jeanconn** [comment] 2017-12-12 17:13
Yes.  That's somewhat been my operating strategy.  I *think* that we only have libgcc 5.2.0 in the current environment because that was the newest lib compatible with the set of packages we installed at the time (so libgcc "floated" up to 5.2.0).   But I don't recall the conda solver's strategy for that.  So still trying to figure out the best way to test the environment to see if it is robust to a downgrade, or.. as you say, decide to rebuild the sherpa conda with libgcc 5.2.0.

**Comment by jeanconn** [comment] 2017-12-12 17:17
Also regarding 

> My educated guess is that libgcc 5.2.0 contains libgfortran.so.3, so when it was downgraded to libgcc 4.8.5 (which doesn't have it) it removed it, ignoring that you also had libgfortran 3.0.0. When you uninstalled installed libgfortran 3.0.0 the library was installed again, and everything could work.

I think this is dead on.  If I make a scratch environment starting with the dependence that libgcc=4.8.5, the sherpa install works without downgrade (expected) and sherpa imports without issue.  

The point of my working with the libgcc=5.2.0 environment to start was that *is* the current environment in /proj/sot/ska3/flight, so I'm trying to test an upgrade strategy for it instead of a clean install.  A clean install may end up safer anyway if we've got hidden `libgfortran`s in `libgcc` packages.

**Comment by olaurino** [comment] 2017-12-12 17:31
There is also a possibility that Sherpa will work with libgcc=5.2.0, tbh. It's pretty obvious if Sherpa doesn't work, and it doesn't take too much to run all the regression tests.

**Comment by olaurino** [comment] 2018-01-11 15:46
@jeanconn any news on this?

**Comment by jeanconn** [comment] 2018-01-11 19:40
Hi @olaurino.  I think we're going to go with your built package and a new environment built from scratch to use libgcc=4.8.5, but haven't promoted it just yet.

**Comment by DougBurke** [comment] 2018-05-18 12:43
Can we close this now?

**Comment by taldcroft** [comment] 2018-05-18 12:54
I *think* so, but should wait for @jeanconn.

**Comment by DougBurke** [comment] 2018-05-18 13:04
https://sd.keepcalm-o-matic.co.uk/i/keep-calm-and-wait-for-godot-29.png

**Comment by jeanconn** [comment] 2018-05-18 13:18
Yes, this can be closed.  The built package works fine for us and the docker setup athttps://github.com/sherpa/legacy-builds should help if we get in a pinch (I had meant to do some test building with that but have not).

**Comment by olaurino** [comment] 2018-05-18 13:19
Thanks @jeanconn!

**Closed by olaurino** 2018-05-18 13:19 UTC
Labels: area:build, note:not-a-bug, type:bug
