### ISSUE TITLE
incorrect doc for levmar

### ISSUE THREAD

**Issue by dtnguyen2** [sherpa/sherpa#182] opened 2016-02-12 19:35 UTC
The doc for levmar:
http://cxc.harvard.edu/sherpa/ahelp/levmar.html
is incorrect.  The value of 1.19209289551e-07 is the correct default value for xtol, gtol and epsfcn; However, the statement
sqrt(DBL_EPSILON ) ~ 1.19209289551e-07
is incorrect; Moreover, the doc should say:
FLOAT_EPSILON ~ 1.19209289551e-07
We should mention that xtol, gtol and epsfcn should set for float precision for most XSpec models (since they are mostly float precision) and the user should set xtol, gtol and epsfcn to DBL_EPSILON if the model functions are double precision like all native sherpa models.

**Comment by dtnguyen2** [comment] 2016-02-12 21:25
Oops, made a typo.  The line:
FLOAT_EPSILON ~ 1.19209289551e-07
should be:
FLT_EPSILON ~ 1.19209289551e-07

sorry about that

**Comment by olaurino** [comment] 2016-05-20 17:53
I believe this is a duplicate of #128. I added #128 to the 4.8.2 milestone rather than closing this one as a duplicate just in case.

**Comment by olaurino** [comment] 2016-08-29 19:59
I am keeping this bug open as a reminder that we need to change the `ahelp` webpage for `levmar`. #128 will be closed when we change the relevant docstring.

**Comment by olaurino** [comment] 2016-10-03 14:43
Should we keep this open and remove the milestone? The ahelp file still lists the wrong values.

**Comment by DougBurke** [comment] 2016-10-03 19:44
I think this should be closed as the fix has been applied to master. The ahelp information is a CIAO-specific thing, and not related to this bug tracker.

**Comment by olaurino** [comment] 2016-10-03 19:46
Then this should have been closed as a duplicate of #128.

**Closed** 2017-07-05 19:41 UTC
Labels: area:docs, note:duplicate, priority:high, type:bug
