### ISSUE TITLE
Problem fitting user defined models with custom fit statistic

### ISSUE THREAD

**Issue by matthewdahmer** [sherpa/sherpa#341] opened 2017-03-03 16:11 UTC
## Summary

I am unable to fit user defined models with a user defined fit statistic calculation in Sherpa version 4.9.0. This works using version 4.7, but stopped working in all versions starting with 4.8.2 through to 4.9.0. The following file can give you an idea of how I am using sherpa in this fashion, however I have a much simpler example below which will make my real-world example make more sense.
https://github.com/sot/xijafit/blob/f5268236f5f22dead2c2ac570b4b3e9234d66e48/xijafit/fit.py

The methods defined in the file above are derived from code originally written by Tom Aldcroft (@taldcroft) to fit these models, and are used to help fit Ska Xija thermal models for Chandra operations.

I believe the error I get is a result of a change made in the commit labeled "generalize Stat API", included in version 4.8.2 where the calc_stat method in the UserStat class was modified so that a valid/proper return value was removed. Please compare line 233 in the first link to line 519 in the second link.

Version 4.7
Look at the function definition on line 233:
https://github.com/sherpa/sherpa/blob/ba26a5f6e7cb9afa999ee2c16b435a6a12f821be/sherpa/stats/__init__.py

Version 4.8.2
Look at the function definition on line 519:
https://github.com/sherpa/sherpa/blob/183084aee89ec828ce872e4c54ad9e021ae23c54/sherpa/stats/__init__.py

Version 4.9.0
Look at the function definition on line 736:
https://github.com/sherpa/sherpa/blob/aa98d19553d1e62d3c65ba5abf33562e5e7dbe4c/sherpa/stats/__init__.py

This change in question was made in the commit labeled "generalize Stat API":
https://github.com/sherpa/sherpa/commit/576085b736a7aafad524dbfc35056283461aae00#diff-568ea47e7d1cda4a6191dbfc20376a45

## Details

First I'll note what does work. Defining a user model using the methodology spelled out in the 1D example in the following link works as expected.

http://cxc.harvard.edu/sherpa/threads/user_model/

I modified the example in the above link to produce the following code which works in version 4.7 and 4.9.0:

```
import sherpa.astro.ui as ui

def myline(pars, x):
    return pars[0] * x + pars[1]

x = np.arange(20)
y = x ** 2
ui.load_arrays(1, x, y)
ui.load_user_model(myline, "myl")
ui.add_user_pars("myl", ["m","b"])
ui.set_model(myl)
myl.m=30
myl.b=20
ui.fit()
ui.plot_fit()
```

My use case is a bit more complex, where I need to define my own methods for updating the model parameters and calculating the fit statistic, along with a custom model that queries the input data directly. Here is a simplified version that demonstrates my use case.

```
import sherpa.astro.ui as ui
import numpy as np

class ExampleModel(object):
    """ Class to define model
    """
    def __init__(self, x, y):
        self.x = np.array(x) # x needs to be an iterable
        self.y = np.array(y) # y needs to be an iterable
        self.parvals = [1, 2] # initial guess
        self.parnames = ("m", "b")

    def calc_stat(self):
        return np.sum(np.abs(self.y - self.model()))

    def model(self):
        return  self.parvals[0] * self.x + self.parvals[1]


class CalcModel(object):
    """ Class to update model parameters
    """
    def __init__(self, model):
        self.model = model

    def __call__(self, pars, x):
        self.model.parvals = pars
        return np.ones_like(x)


class CalcStat(object):
    """ Class to determine fit statistic
    """
    def __init__(self, model):
        self.model = model
        self.min_fit_stat = None
        self.min_par_vals = self.model.parvals

    def __call__(self, _data, _model, *args, **kwargs):
        fit_stat = self.model.calc_stat()

        if self.min_fit_stat is None or fit_stat < self.min_fit_stat:
            self.min_fit_stat = fit_stat
            self.min_parvals = self.model.parvals

        print('\n FIT STAT = {}\n'.format(fit_stat))

        return fit_stat, np.ones(1)


xdata = np.arange(20)
ydata = xdata ** 2
newmodel = ExampleModel(xdata, ydata)

dummy_data = np.zeros(1)
dummy_times = np.arange(1)
ui.load_arrays(1, dummy_times, dummy_data)

method = 'simplex'
ui.set_method(method)

ui.load_user_model(CalcModel(newmodel), 'simplemodel')
ui.add_user_pars('simplemodel', newmodel.parnames)
ui.set_model(1, 'simplemodel')

calc_stat = CalcStat(newmodel)
ui.load_user_stat('customstat', calc_stat, lambda x: np.ones_like(x))
ui.set_stat(customstat)

ui.fit(1)
```

This example works in version 4.7, however I get the error trace shown below when using version 4.9.0, but only after I run the `ui.fit(1)` command, I do not receive any errors prior to running this fit command. I did not test my example code in 4.8.2, however I did confirm I get a very similar error in that version when running my real-world case. 

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-34-d42e83603d80> in <module>()
----> 1 ui.fit(1)

<string> in fit(id, *otherids, **kwargs)

/proj/sot/ska/dev/arch/x86_64h-darwin-10.12/lib/python3.5/site-packages/sherpa/astro/ui/utils.py in fit(self, id, *otherids, **kwargs)
   9260         """
   9261         kwargs['bkg_only'] = False
-> 9262         self._fit(id, *otherids, **kwargs)
   9263
   9264     def fit_bkg(self, id=None, *otherids, **kwargs):

/proj/sot/ska/dev/arch/x86_64h-darwin-10.12/lib/python3.5/site-packages/sherpa/astro/ui/utils.py in _fit(self, id, *otherids, **kwargs)
   9364                     i).mask & numpy.isfinite(self.get_data(i).get_x())
   9365
-> 9366         res = f.fit(**kwargs)
   9367         res.datasets = ids
   9368         self._fit_results = res

/proj/sot/ska/dev/arch/x86_64h-darwin-10.12/lib/python3.5/site-packages/sherpa/fit.py in run(fit, *args, **kwargs)
     57     def run(fit, *args, **kwargs):
     58         fit.model.startup()
---> 59         result = func(fit, *args, **kwargs)
     60         fit.model.teardown()
     61         return result

/proj/sot/ska/dev/arch/x86_64h-darwin-10.12/lib/python3.5/site-packages/sherpa/fit.py in fit(self, outfile, clobber)
   1099             raise FitErr('statnotforbackgsub', self.stat.name)
   1100
-> 1101         init_stat = self.calc_stat()
   1102         # output = self.method.fit ...
   1103         output = self._iterfit.fit(self._iterfit._get_callback(outfile, clobber),

/proj/sot/ska/dev/arch/x86_64h-darwin-10.12/lib/python3.5/site-packages/sherpa/fit.py in calc_stat(self)
   1014         #     shell.interact()
   1015
-> 1016         return self._calc_stat()[0]
   1017
   1018     def calc_chisqr(self):

TypeError: 'NoneType' object is not subscriptable
```

This is telling me that the `_calc_stat` function has a return value of `None`, suggesting my custom fit statistic method, as defined using the `CalcStat` class in my example, is missing or not set properly. This is the clue that led me to the theory I stated above in the summary, please let me know if my theory is not accurate or if I am missing an important step that would fix my problem.

Thank You,
Matthew Dahmer

**Comment by olaurino** [comment] 2017-03-03 17:32
Matthew, thank you for your report. Apparently, one of our recent changes triggered an unintended regression, despite our attempts to make the change backward compatible.

I'll need to look a little bit more into it, but your report is very accurate and so very helpful. I really appreciate the time you took to debug the issue before sending the bug report.

I think today I will have time to try and reproduce the issue so I have a new test case I can work with, but I am not sure I will be able to look into a fix until next week.

Again, thank you for this report and sorry for the inconvenience.

**Comment by matthewdahmer** [comment] 2017-03-03 18:28
Hi Omar,

Next week is fine for a fix, I have access to an installation of version 4.7 so I can use this as a workaround. Please let me know if/when you would like me to test any updates.

Thank You!
Matt

**Comment by olaurino** [comment] 2017-03-03 20:06
Matthew, it looks like I can't reproduce the issue using the script that you posted.

Just to make sure we are running the same code, I created a new conda environment like this:

````
conda create -n test-341 -c sherpa sherpa=4.9.0 python=3.5
````

The I ran the following script (if it looks silly it's because it started as a unit test, but it is just wrapping your code):

```` python
import numpy as np

from sherpa.astro import ui


def test_341():
    class ExampleModel(object):
        """ Class to define model
        """
        def __init__(self, x, y):
            self.x = np.array(x) # x needs to be an iterable
            self.y = np.array(y) # y needs to be an iterable
            self.parvals = [1, 2] # initial guess
            self.parnames = ("m", "b")

        def calc_stat(self):
            return np.sum(np.abs(self.y - self.model()))

        def model(self):
            return  self.parvals[0] * self.x + self.parvals[1]


    class CalcModel(object):
        """ Class to update model parameters
        """
        def __init__(self, model):
            self.model = model

        def __call__(self, pars, x):
            self.model.parvals = pars
            return np.ones_like(x)


    class CalcStat(object):
        """ Class to determine fit statistic
        """
        def __init__(self, model):
            self.model = model
            self.min_fit_stat = None
            self.min_par_vals = self.model.parvals

        def __call__(self, _data, _model, *args, **kwargs):
            fit_stat = self.model.calc_stat()

            if self.min_fit_stat is None or fit_stat < self.min_fit_stat:
                self.min_fit_stat = fit_stat
                self.min_parvals = self.model.parvals

            print('\n FIT STAT = {}\n'.format(fit_stat))

            return fit_stat, np.ones(1)


    xdata = np.arange(20)
    ydata = xdata ** 2
    newmodel = ExampleModel(xdata, ydata)

    dummy_data = np.zeros(1)
    dummy_times = np.arange(1)
    ui.load_arrays(1, dummy_times, dummy_data)

    method = 'simplex'
    ui.set_method(method)

    ui.load_user_model(CalcModel(newmodel), 'simplemodel')
    ui.add_user_pars('simplemodel', newmodel.parnames)
    ui.set_model(1, 'simplemodel')

    calc_stat = CalcStat(newmodel)
    ui.load_user_stat('customstat', calc_stat, lambda x: np.ones_like(x))
    ui.set_stat(customstat)

    ui.fit(1)

test_341()
````
and I got the following traceback:

````
WARNING: imaging routines will not be available, 
failed to import sherpa.image.ds9_backend due to 
'RuntimeErr: DS9Win unusable: Could not find ds9 on your PATH'
WARNING: failed to import sherpa.plot.pylab_backend; plotting routines will not be available
WARNING: failed to import sherpa.astro.io; FITS I/O routines will not be available
WARNING: failed to import sherpa.astro.xspec; XSPEC models will not be available
Traceback (most recent call last):
  File "/export/working/sherpa/sherpa/stats/tests/test_user_stat.py", line 93, in <module>
    test_341()
  File "/export/working/sherpa/sherpa/stats/tests/test_user_stat.py", line 91, in test_341
    ui.fit(1)
  File "<string>", line 1, in fit
  File "/export/miniconda/miniconda/envs/test-341/lib/python3.5/site-packages/sherpa/astro/ui/utils.py", line 9303, in fit
    self._fit(id, *otherids, **kwargs)
  File "/export/miniconda/miniconda/envs/test-341/lib/python3.5/site-packages/sherpa/astro/ui/utils.py", line 9407, in _fit
    res = f.fit(**kwargs)
  File "/export/miniconda/miniconda/envs/test-341/lib/python3.5/site-packages/sherpa/fit.py", line 51, in run
    result = func(fit, *args, **kwargs)
  File "/export/miniconda/miniconda/envs/test-341/lib/python3.5/site-packages/sherpa/fit.py", line 1081, in fit
    init_stat = self.calc_stat()
  File "/export/miniconda/miniconda/envs/test-341/lib/python3.5/site-packages/sherpa/fit.py", line 996, in calc_stat
    return self._calc_stat()[0]
  File "/export/miniconda/miniconda/envs/test-341/lib/python3.5/site-packages/sherpa/fit.py", line 977, in _calc_stat
    return self.stat.calc_stat(self.data, self.model)
  File "/export/miniconda/miniconda/envs/test-341/lib/python3.5/site-packages/sherpa/stats/__init__.py", line 737, in calc_stat
    raise StatErr('nostat', self.name, 'calc_stat()')
sherpa.utils.err.StatErr: User statistic 'customstat' has no calc_stat() function
````

Note, it's still a regression, because the very same script seems to work in 4.7 (in the sense that it does not error out and it performs a fit, I didn't check the results), but it's a different error than the one you reported.

I am still looking into it, but it would help to understand why we are getting different errors.

Also, the line numbers do not match: in my environment (sherpa 4.9.0) the error you reported would be at line 996, not 1016.

What does:
````
python -c "import sherpa; print(sherpa.__file__)"
````

outputs if you run it?

**Comment by olaurino** [comment] 2017-03-03 20:18
Sorry, that was meant to be:

````
python -c "import sherpa; print(sherpa.__version__)"
````

**Comment by matthewdahmer** [comment] 2017-03-03 21:17
So it looks like I made a rookie mistake in assuming I was using one version when in fact I was using a different one. The error I reported above is obtained using version 4.8.2 (found using the command you requested I run). I confirmed the different traceback you reported is what I get on 4.9.0. Thank you for pointing that out.

Although the original error trace I posted (for 4.8.2) lists the error at line 1016 in sherpa/fit.py, I was suggesting in my summary above that the actual problem can be traced back to line 519 (version 4.8.2) in sherpa/stats/__init__.py since this is where I noticed a change to the UserStat class between version 4.7 and 4.8.2. 

The line number you see for the final error in the traceback you posted is consistent with the line number I pointed out in my original summary for 4.9.0. I think both trackbacks are pointing to the same issue. In sherpa/stats/__init__.py, version 4.8.2 includes a test to see if the user defined statistic is set, `line 520: if not self._statfuncset:`, this is missing in 4.9.0 (near line 736). So perhaps it is being recorded as set...but not fully. The presence of the `raise StatErr('nostat', self.name, 'calc_stat()')` syntax suggests to me that the intention was that the entire `calc_stat` method would be overwritten in this case.

**Comment by olaurino** [comment] 2017-03-04 13:27
Thank you for the additional information. I agree with your analysis. I was able to find a potential fix before I left yesterday. I'll issue a PR soon. We also need to make sure that our documentation on user statistics is consistent.

**Comment by olaurino** [comment] 2017-03-06 15:27
@matthewdahmer I just issued PR #343 which should solve your issue. Please let me know if you have any problems and if it does resolve the original issue.

**Comment by matthewdahmer** [comment] 2017-03-07 19:30
Hi @olaurino, not sure if you'd prefer I comment here or in the PR page, I'll repost if you'd prefer it on the PR page.

I note that it was mentioned that there's an issue with the fit statistic not being a float. This is not a problem for me as I can always force it to be a float if need be. In fact, in my real world example it is a float. That being said, when I force the return value to be a float, the test case runs but does not fit the curve, instead it computes the same fit statistic over and over and returns zeros for the parameters.

**Comment by olaurino** [comment] 2017-03-07 19:50
@matthewdahmer what I meant in the description of the PR is that after the alleged fix is in place, the test case your posted still does not work because of the float/int issue, as far as I can tell. When casting the stat to float, it runs.

I'll need to take a better look at your test case and rerun it against an old version to see what is wrong.

**Comment by olaurino** [comment] 2017-03-07 21:37
@matthewdahmer I might well be missing something here, but it looks like your script sets the data to a single bin with values (x, y) = (1, 0), so I am not surprised the model parameters end up being zero. There might be other issues, though. I'll come up with a realistic test and add it to #343. I would be interested in knowing if #343 fixes your real code.

**Comment by matthewdahmer** [comment] 2017-03-07 23:35
@olaurino I'll try out #343 tonight or tomorrow morning hopefully.

The (1, 0) values are meant to be dummy values are not intended to be used. This is where I think I am setting this dummy data, it is my understanding that sherpa expects this to be set regardless of whether or not it is used:

```
dummy_data = np.zeros(1)
dummy_times = np.arange(1)
ui.load_arrays(1, dummy_times, dummy_data)
```

I want the fit statistic to use the x and y data stored in the`ExampleModel` at the time it is created/initialized, not this dummy/placeholder data. This is done because the data is fetched and formatted by the model class in the real world case, and the fit statistic is also calculated within this model.

This is where I am expecting the "real" x, y data to be set:
```
xdata = np.arange(20)
ydata = xdata ** 2
newmodel = ExampleModel(xdata, ydata)
```
This then gets saved to the x, y attributes in the `ExampleModel` class when initialized and is used by the internal/custom fit statistic calculation `calc_stat` in my model.

**Comment by matthewdahmer** [comment] 2017-03-08 17:49
@olaurino, I tested #343 and unfortunately this update does not address the issue in my most recent comment.

**Comment by olaurino** [comment] 2017-03-08 18:12
I see what you mean. I believe I ran your test code against 4.7 and got the same 0 result, though, that's why I didn't look into it any further to check what the code was doing. I'll check again, and in any case there is still at least one issue I have to fix in #343.

**Comment by olaurino** [comment] 2017-03-08 18:23
I can see meaningful results when running the test script in 4.7. Not sure what I tested the other day, then. I'll keep you posted, @matthewdahmer.

**Comment by olaurino** [comment] 2017-03-09 15:51
Tracking down this issue was quite a bumpy ride, but I guess I now know what's happening.

It's all related to the addition of the `wstat` statistic, and the changes that were required to make it work.

First, #195 changed `UserStat` so that the function did not return anything any more. Then, the refactoring performed in #287:

   * removed code that always evaluated the model before calling the statistic method, leaving such step to the statistic classes themselves.
   * started passing the whole data and model objects to the statistic methods, leaving it to them to figure out what info to extract and how.

In the meantime, the `UserStat.calc_stat` function was not being updated (or updated under wrong assumptions), which lead to it lagging behind broken.

I am committing more changes to #343. While I would hope the new commits to fix this issue in all its forms, I would still like to do some refactoring to avoid code repetitions and make the code more maintainable. More info in the PR page.

**Comment by matthewdahmer** [comment] 2017-03-09 23:41
@olaurino Wow thank you for spending the time to get to the bottom of this issue! PR #343 seems to work on my test case, I get identical results using 4.7 and PR #343. I'm still assembling a test environment for my real world case, which is proving a little more difficult than I anticipated, but I hope to have that ready tomorrow.

**Comment by matthewdahmer** [comment] 2017-03-10 22:49
@olaurino Preliminary tests in the full test environment look good. I am putting together a more formal test at the moment.

**Comment by matthewdahmer** [comment] 2017-03-18 14:02
@olaurino Sorry for the delay, my more formal test worked perfectly. PR #343 fixes the issue I was having, thank you!

**Closed** 2017-07-11 17:30 UTC
Labels: area:code, general:statistics, type:bug
