### ISSUE TITLE
importing stk or group modules cause segfault on macOS Mojave

### ISSUE THREAD

**Issue by neobar** [sherpa/sherpa#720] opened 2019-12-21 19:47 UTC
Hi, 
The OS is macOS Mojave, and python version is 3.7.4, Anaconda.
I have this problem after building sherpa.
Xspec models are not configured.

$ sherpa_test
Requirement already satisfied: pytest!=5.2.3,>=3.3 in ./anaconda3/lib/python3.7/site-packages (5.3.2)
Requirement already satisfied: py>=1.5.0 in ./anaconda3/lib/python3.7/site-packages (from pytest!=5.2.3,>=3.3) (1.8.0)
Requirement already satisfied: packaging in ./anaconda3/lib/python3.7/site-packages (from pytest!=5.2.3,>=3.3) (19.2)
Requirement already satisfied: attrs>=17.4.0 in ./anaconda3/lib/python3.7/site-packages (from pytest!=5.2.3,>=3.3) (19.3.0)
Requirement already satisfied: more-itertools>=4.0.0 in ./anaconda3/lib/python3.7/site-packages (from pytest!=5.2.3,>=3.3) (8.0.2)
Requirement already satisfied: pluggy<1.0,>=0.12 in ./anaconda3/lib/python3.7/site-packages (from pytest!=5.2.3,>=3.3) (0.13.1)
Requirement already satisfied: wcwidth in ./anaconda3/lib/python3.7/site-packages (from pytest!=5.2.3,>=3.3) (0.1.7)
Requirement already satisfied: importlib-metadata>=0.12 in ./anaconda3/lib/python3.7/site-packages (from pytest!=5.2.3,>=3.3) (1.3.0)
Requirement already satisfied: pyparsing>=2.0.2 in ./anaconda3/lib/python3.7/site-packages (from packaging->pytest!=5.2.3,>=3.3) (2.4.5)
Requirement already satisfied: six in ./anaconda3/lib/python3.7/site-packages (from packaging->pytest!=5.2.3,>=3.3) (1.13.0)
Requirement already satisfied: zipp>=0.5 in ./anaconda3/lib/python3.7/site-packages (from importlib-metadata>=0.12->pytest!=5.2.3,>=3.3) (0.6.0)
=============================================================================================== test session starts ================================================================================================
platform darwin -- Python 3.7.4, pytest-5.3.2, py-1.8.0, pluggy-0.13.1
rootdir: /Users/sxz89
plugins: astropy-header-0.1.1, arraydiff-0.3, remotedata-0.3.2, openfiles-0.4.0, asdf-2.4.2, doctestplus-0.5.0, hypothesis-4.54.2
collecting ... Fatal Python error: Segmentation fault

**Comment by DougBurke** [comment] 2019-12-22 17:12
What version are you using (e.g. `master` branch or a release)?

```
% python -c 'from sherpa._version import get_versions; print(get_versions())'
```

**Comment by DougBurke** [comment] 2019-12-23 14:47
I see a crash with the master branch, anaconda with a python 3.7 build.

```
% python setup.py develop
...
% python setup.py test
...
============================================================= test session starts =============================================================
platform darwin -- Python 3.7.5, pytest-5.3.2, py-1.8.0, pluggy-0.13.1
rootdir: /Users/dburke/build/sherpa, inifile: pytest.ini
plugins: xvfb-1.2.0
collecting ... Fatal Python error: Segmentation fault

Current thread 0x000000010f8205c0 (most recent call first):
  File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 1043 in create_module
  File "<frozen importlib._bootstrap>", line 583 in module_from_spec
  File "<frozen importlib._bootstrap>", line 670 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 967 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 983 in _find_and_load
  File "/Users/dburke/build/sherpa/sherpa/astro/data.py", line 55 in <module>
  File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 728 in exec_module
  File "<frozen importlib._bootstrap>", line 677 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 967 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 983 in _find_and_load
  File "/Users/dburke/build/sherpa/sherpa/instrument.py", line 26 in <module>
  File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 728 in exec_module
  File "<frozen importlib._bootstrap>", line 677 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 967 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 983 in _find_and_load
  File "/Users/dburke/build/sherpa/sherpa/all.py", line 56 in <module>
  File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 728 in exec_module
  File "<frozen importlib._bootstrap>", line 677 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 967 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 983 in _find_and_load
  File "/Users/dburke/build/sherpa/sherpa/astro/ui/__init__.py", line 20 in <module>
  File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 728 in exec_module
  File "<frozen importlib._bootstrap>", line 677 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 967 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 983 in _find_and_load
  File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1035 in _handle_fromlist
  File "/Users/dburke/build/sherpa/sherpa/astro/datastack/tests/test_datastack.py", line 28 in <module>
  File "/Users/dburke/build/sherpa/.eggs/pytest-5.3.2-py3.7.egg/_pytest/assertion/rewrite.py", line 143 in exec_module
  File "<frozen importlib._bootstrap>", line 677 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 967 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 983 in _find_and_load
  File "/Users/dburke/build/sherpa/.eggs/py-1.8.0-py3.7.egg/py/_path/local.py", line 701 in pyimport
  File "/Users/dburke/build/sherpa/.eggs/pytest-5.3.2-py3.7.egg/_pytest/python.py", line 492 in _importtestmodule
  File "/Users/dburke/build/sherpa/.eggs/pytest-5.3.2-py3.7.egg/_pytest/python.py", line 424 in _getobj
  File "/Users/dburke/build/sherpa/.eggs/pytest-5.3.2-py3.7.egg/_pytest/python.py", line 248 in obj
  File "/Users/dburke/build/sherpa/.eggs/pytest-5.3.2-py3.7.egg/_pytest/python.py", line 440 in _inject_setup_module_fixture
  File "/Users/dburke/build/sherpa/.eggs/pytest-5.3.2-py3.7.egg/_pytest/python.py", line 427 in collect
  File "/Users/dburke/build/sherpa/.eggs/pytest-5.3.2-py3.7.egg/_pytest/runner.py", line 254 in <lambda>
  File "/Users/dburke/build/sherpa/.eggs/pytest-5.3.2-py3.7.egg/_pytest/runner.py", line 234 in from_call
  File "/Users/dburke/build/sherpa/.eggs/pytest-5.3.2-py3.7.egg/_pytest/runner.py", line 254 in pytest_make_collect_report
  File "/Users/dburke/build/sherpa/.eggs/pluggy-0.13.1-py3.7.egg/pluggy/callers.py", line 187 in _multicall
  File "/Users/dburke/build/sherpa/.eggs/pluggy-0.13.1-py3.7.egg/pluggy/manager.py", line 87 in <lambda>
  File "/Users/dburke/build/sherpa/.eggs/pluggy-0.13.1-py3.7.egg/pluggy/manager.py", line 93 in _hookexec
  File "/Users/dburke/build/sherpa/.eggs/pluggy-0.13.1-py3.7.egg/pluggy/hooks.py", line 286 in __call__
  File "/Users/dburke/build/sherpa/.eggs/pytest-5.3.2-py3.7.egg/_pytest/runner.py", line 373 in collect_one_node
  File "/Users/dburke/build/sherpa/.eggs/pytest-5.3.2-py3.7.egg/_pytest/main.py", line 717 in genitems
  File "/Users/dburke/build/sherpa/.eggs/pytest-5.3.2-py3.7.egg/_pytest/main.py", line 492 in _perform_collect
  File "/Users/dburke/build/sherpa/.eggs/pytest-5.3.2-py3.7.egg/_pytest/main.py", line 454 in perform_collect
  File "/Users/dburke/build/sherpa/.eggs/pytest-5.3.2-py3.7.egg/_pytest/main.py", line 255 in pytest_collection
  File "/Users/dburke/build/sherpa/.eggs/pluggy-0.13.1-py3.7.egg/pluggy/callers.py", line 187 in _multicall
  File "/Users/dburke/build/sherpa/.eggs/pluggy-0.13.1-py3.7.egg/pluggy/manager.py", line 87 in <lambda>
  File "/Users/dburke/build/sherpa/.eggs/pluggy-0.13.1-py3.7.egg/pluggy/manager.py", line 93 in _hookexec
  File "/Users/dburke/build/sherpa/.eggs/pluggy-0.13.1-py3.7.egg/pluggy/hooks.py", line 286 in __call__
  File "/Users/dburke/build/sherpa/.eggs/pytest-5.3.2-py3.7.egg/_pytest/main.py", line 245 in _main
  File "/Users/dburke/build/sherpa/.eggs/pytest-5.3.2-py3.7.egg/_pytest/main.py", line 196 in wrap_session
  File "/Users/dburke/build/sherpa/.eggs/pytest-5.3.2-py3.7.egg/_pytest/main.py", line 239 in pytest_cmdline_main
  File "/Users/dburke/build/sherpa/.eggs/pluggy-0.13.1-py3.7.egg/pluggy/callers.py", line 187 in _multicall
  File "/Users/dburke/build/sherpa/.eggs/pluggy-0.13.1-py3.7.egg/pluggy/manager.py", line 87 in <lambda>
  File "/Users/dburke/build/sherpa/.eggs/pluggy-0.13.1-py3.7.egg/pluggy/manager.py", line 93 in _hookexec
  File "/Users/dburke/build/sherpa/.eggs/pluggy-0.13.1-py3.7.egg/pluggy/hooks.py", line 286 in __call__
  File "/Users/dburke/build/sherpa/.eggs/pytest-5.3.2-py3.7.egg/_pytest/config/__init__.py", line 92 in main
  File "/Users/dburke/build/sherpa/helpers/test.py", line 55 in run_tests
  File "/Users/dburke/miniconda3/envs/sherpa37/lib/python3.7/site-packages/setuptools/command/test.py", line 237 in run
  File "/Users/dburke/miniconda3/envs/sherpa37/lib/python3.7/distutils/dist.py", line 985 in run_command
  File "/Users/dburke/miniconda3/envs/sherpa37/lib/python3.7/distutils/dist.py", line 966 in run_commands
  File "/Users/dburke/miniconda3/envs/sherpa37/lib/python3.7/distutils/core.py", line 148 in setup
  File "/Users/dburke/miniconda3/envs/sherpa37/lib/python3.7/site-packages/setuptools/__init__.py", line 145 in setup
  File "/Users/dburke/miniconda3/envs/sherpa37/lib/python3.7/site-packages/numpy/distutils/core.py", line 171 in setup
  File "setup.py", line 148 in <module>
Segmentation fault: 11
```

This is with  `Darwin Kernel Version 18.6.0` - which I believe is also macOS Mojave.

What is the difference to out Travis/CI run that lets that pass but shows the problem here, I wonder?

**Comment by DougBurke** [comment] 2019-12-23 15:01
So, it looks like it's the `group` module:

```
% python -c 'import group'
Segmentation fault: 11
```

This is an optional module, only used for PHA analysis, but unfortunately we don't have a way to say "don't even try to load this module".

It is also a problem for the other "OTS" lib we include, the `stk` module:

```
% python -c 'import stk'
Segmentation fault: 11
```

However, it's not all compiled modules, since this doesn't crash:

```
% python -c 'import sherpa.astro.utils._region'
```

**Comment by DougBurke** [comment] 2019-12-23 15:14
Using Python 3.6 instead of Python 3.7 I also get a crash, but with a sightly-different error message:

```
% python -c 'import stk'
Fatal Python error: PyThreadState_Get: no current thread

Abort trap: 6
```

**Comment by neobar** [comment] 2019-12-23 16:11
> What version are you using (e.g. `master` branch or a release)?
> 
> ```
> % python -c 'from sherpa._version import get_versions; print(get_versions())'
> ```
{'version': '4.11.1+254.g519e43a2-py3.7-macosx-10.9-x86_64.egg', 'full': ''}

I also tried the 4.12.0.tar.gz. Same error.

**Comment by olaurino** [comment] 2019-12-23 17:48
@neobar when you build on macOS using the conda compilers you need to set `PYTHON_LDFLAGS=' '` (note that's a space, not an empty string).

I thought we had that in the docs, but I couldn't find it.

**Comment by DougBurke** [comment] 2019-12-23 18:28
I can confirm that on my build

```
% export PYTHON_LDFLAGS=' '
```

made `python setup.py` pass/not crash. I'll see about adding it to the build/install instructions.

**Comment by neobar** [comment] 2019-12-23 18:29
Yes, before building source code, I run

```bash
export PYTHON_LDFLAGS=' '
```

Previous error gone.
Thanks. 
@DougBurke @olaurino

**Comment by DougBurke** [comment] 2019-12-23 19:00
@neobar glad that it's working for you now. Please let us know if there are more problems (or, even better, successes) with using Sherpa!

**Comment by DougBurke** [comment] 2019-12-23 19:02
I've created #721 to update the documentation, and will leave this issue open until #721 is merged (there's the hope we can update the build to avoid the need of setting this environment variable on macOS with anaconda, but that's a longer-term change).

**Closed** 2020-01-17 20:37 UTC
Labels: type:bug
