### ISSUE TITLE
Debian package for Sherpa

### ISSUE THREAD

**Issue by cdeil** [sherpa/sherpa#75] opened 2015-08-11 09:56 UTC
This Friday I'll join the [Debian Astro packaging tutorial](https://wiki.debian.org/Sprints/2015/Astro) by @olebole and I'd like to try and create a Debian package for Sherpa 4.7.

The maintainer for the package will be the "Debian Astronomy Team" as explained [here](https://wiki.debian.org/DebianAstro/AstropyPackagingTutorial/Preparation). Anyone interested to follow this or help out is welcome to join their mailing list.

OK? Or are there any reasons not to do it or work in progress to add it already?

And would it be OK if I use this issue to ask for advice if any issues come up during packaging?

**Comment by cdeil** [comment] 2015-08-11 12:55
I hadn't see #3 ... this issue is basically a duplicate.

@olebole – Is the fact that Sherpa currently installs `group.so` and `stk.so` outside the `sherpa` folder (see #50) an issue? Is this acceptable for Debian packaging or do we need to / should we patch the build scripts to change this?

**Comment by olebole** [comment] 2015-08-11 12:59
I would consider this as a bug, but not as a showstopper as long as it does not conflict with other Debian packages. If you have a patch, it would be nice, however :-)

**Comment by cdeil** [comment] 2015-08-11 13:03
I don't have a patch and I'm not very familiar with the Sherpa build yet.
So if not fixing / patching this in the Debian package is an acceptable option, that would be my preference.

**Comment by anetasie** [comment] 2015-08-11 13:08
@cdeil nobody is currently working on the debian packaging. #50 is being worked on and there will be a patch at some point, but not in immediate future, because of the connection to the CIAO build.

**Comment by olaurino** [comment] 2015-08-11 13:16
I am closing this one as it is a duplicate of #3.

**Closed by olaurino** 2015-08-11 13:16 UTC
Labels: area:other, note:duplicate, type:question
