### ISSUE TITLE
loading pha with energy_lo=0 gives nan/inf

### ISSUE THREAD

**Issue by JohannesBuchner** [sherpa/sherpa#332] opened 2017-01-19 21:38 UTC
Not sure if this has been addressed in another bug already.

When loading a pha file where the lowest energy bins starts at 0 (e.g. 0-0.01), calc_stat returns a nan/inf if cstat is selected. I think this is because some models try to integrate and divide by 0.

This occurs for all files downloaded from swift.ac.uk.
You can find some example files: https://github.com/JohannesBuchner/BXA/tree/feature-auto/examples/sherpa/swift

A workaround is:
load_pha(id, 'interval0pc.pi')
if get_rmf(id).energ_lo[0] == 0: get_rmf(id).energ_lo[0] = 0.01
if get_arf(id).energ_lo[0] == 0: get_arf(id).energ_lo[0] = 0.01

xspec handles this gracefully.

**Comment by olaurino** [comment] 2017-01-20 16:11
@JohannesBuchner thanks for your report (and for BXA!).

If the issue is with the models, there are probably more options we might consider, from issuing warnings to providing a way for users to handle NaNs coming from models or to set the minimum energy value when the energy is 0. Do you happen to know how XSPEC handles this case, if it does?

If you agree, I would consider this as an RFE to provide ways of handling this case.

Considering that the problem seems to be with the models, unless there are models in Sherpa itself that divide by zero, it looks to me like this is more of a error handling issue than an actual bug.

And please feel free to provide requirements on how you think Sherpa should behave, or any other comments or suggestions.

**Comment by JohannesBuchner** [comment] 2017-01-20 16:41
Wow, someone knows about BXA :) I am honoured. (btw, it will have pretty amazing features in the next version)

A first, simple way to help would be to warn the user when files are loaded, and perhaps link to a web page that explains the problem and how to solve it. Users can easily fix the ARF/RMF files easily with the following python script, passing RMF and ARF files as parameters: https://raw.githubusercontent.com/JohannesBuchner/BXA/feature-auto/fixrespzeros.py 

xspec replaces zeros with a very small value on loading to circumvent this and prints a notice on loading:

```
XSPEC12>data interval0pc.pi
***Warning: Detected response matrix energy bin value = 0 (or neg).
     XSPEC will instead use small finite value (response file will not be altered).

1 spectrum  in use
...
```

One problem with the current sherpa behaviour is that it is hard to track down the issue, because it occurs many steps after the loading, when doing the first fit or calc_stat.

**Comment by DougBurke** [comment] 2017-01-20 16:46
The handling of non-standard responses (e.g. with an energy grid that goes
to 0) is one that can cause a lot of discussion; I believe ISIS either
errors out or provides a warning. That is to say we need some thought about
how to fix/improve the current situation, which is not ideal!

Doug

**Comment by DougBurke** [comment] 2017-06-06 23:02
XSPEC - at least in HEASOFT 6.19 - uses a value of 1.17549e-38 as a check (and really assumes there's only one such bin). I'm going to look into adding a similar check (at least once #358 lands, so that I can guarantee there's a swift data set available for testing that shows this issue).

**Comment by DougBurke** [comment] 2017-07-31 13:17
Now that #358 has landed, the following script (when run from the base sherpa directory) shows the issue - in that there's warnings about  a dividion by 0 due to the e=0 bin (not the exact problem that @JohannesBuchner reported, but I've found that the behavior here seems to be quite sensitive to what exactly is done):

```
% cat err.py 
from sherpa.astro import ui
ui.load_pha('sherpa-test-data/sherpatest/target_sr.pha')
ui.load_arf('sherpa-test-data/sherpatest/target_sr.arf')
ui.load_rmf('sherpa-test-data/sherpatest/swxpc0to12s6_20130101v014.rmf.gz')
ui.set_source(ui.powlaw1d.pl)
s0 = ui.calc_stat()
print('---')
print('stat={}'.format(s0))
print('---')
ui.set_stat('cstat')
s1 = ui.calc_stat()
print('stat={}'.format(s1))
print('---')
```
gives

```
% python err.py 
/home/djburke/sherpa/sherpa-fix-invalid-ogip-responses/sherpa/astro/instrument.py:242: RuntimeWarning: divide by zero encountered in true_divide
  self.lo, self.hi = DataPHA._hc / self.ehi, DataPHA._hc / self.elo
---
stat=722908286.2342303
---
stat=2187220.832765766
---
```

**Comment by DougBurke** [comment] 2017-08-08 00:20
@JohannesBuchner if you get time could you see if #383 

a) works for you
b) seems sensible

**Comment by JohannesBuchner** [comment] 2017-08-08 07:13
@DougBurke I can not install and test the code at the moment, but that seems perfectly sensible and the behaviour I would prefer.

**Comment by DougBurke** [comment] 2017-08-08 11:43
@JohannesBuchner - thanks for looking.

**Closed** 2018-02-08 19:58 UTC
Labels: area:science, dep:xspec, general:statistics, type:enhancement
