### ISSUE TITLE
Add regression test for fix #759

### ISSUE THREAD

**Issue by hamogu** [sherpa/sherpa#760] opened 2020-03-17 00:41 UTC
In #746 I reported a problem with the build-in models. That bug was fixed in #759, which itself reverts PR #444 .

This issue is to remind us to add a regression test to prevent a failure like this sneaking in again in future code changes. (The test could be much more generic than the specific failure in #746).

**Comment by DougBurke** [comment] 2020-03-17 02:16
Indeed. I am currently trying to diagnose why your case caused a problem so that we can have a sensible regression test (but not being particulary successful). If not I think we can use the existing 3c120 data in our test suite to "re-create" the issue.

**Comment by hamogu** [comment] 2020-03-17 03:05
The underlying problem was that the reported fit statistic did not change (whatever the reason - caching in this case, but could be others). That's something that we can systematically test. Unfortunately, I'm home with a 5 year old, limiting my time to work, but here is my idea in pseudo code:
```
# Test 1
# Test that changes in model parameters change fit values
dummydata = ui.Data1D(np.arange(0, 100, .1), 2 * np.ones(1000))  # wide range
for model in ui.list_models():
    testmod = model(name='blablabla')
    oldstat = ui.get_stat_info()
    for par in testmod.pars:
        par.val = 10 * par.val
    newstat = ui.get_stat_info()
    assert oldstat != newstat

# Test 2
# Test that fit actually changes model values and statistics change when model values change
dummydata = ui.Data1D(np.arange(0, 100, .1), 2 * np.ones(1000))  # wide range
for model in ui.list_models():
    testmod = model(name='blablabla')
    oldstat = ui.get_stat_info()
    ui.fit(outfile='temp.txt')
    newstat = ui.get_stat_info()
    assert oldstat != newstat
    assert not all values in second column of temp.txt are equal
```
There is obviously a lot of tuning missing here, but in principle that systematically tests that fits do something for all models.

Extra thoughts:

- No need to wait till fit converges. 10 function evaluations are enough to see if anything happens.
- Not sure that makes sense for multiplicative models. Might have to do `if issubclass(MultiplicativeModel): testmod = model() * const1D`
- Default parameters might not work for all model with the datarange that I suggest. Might need a dict `{'modelname': Data1D(x_range_that_works, y_range_that_works}` listing those.
- In fact, might need to blacklist a few models from testing that don't work easily (some convolution models), but would prefer to black list instead of white list, because that means that any new models added to Sherpa later will be picked up by this test and if it fails they have to be actively blacklisted.
- Instead of `temp.txt` might want to use `StringIO` streams.

**Comment by hamogu** [comment] 2020-03-17 03:07
Not sure I have time to turn that into actual code in the forseeable future (that's why I opened this as an issue and leave notes here now).

**Comment by DougBurke** [comment] 2020-03-17 11:54
Moritz,

The issue to me is why our existing tests didn't catch this regression. We
do have tests that check a fit has "worked" (for some degree of worked).

Doug

**Comment by DougBurke** [comment] 2020-03-17 12:41
I am pretty sure that the problem is down to the analysis=wavelength setting, since I can get sensible behavior (before #759 was merged, e.g. with CIAO 4.12) with the following

```python
from sherpa.astro import ui

path = ''
ui.load_data(path + 'pha2.gz')
ui.load_arf(10, path+"meg_1.arf.gz")
ui.load_rmf(10, path+"meg_1.rmf.gz")

d10 = ui.get_data(10)

# ui.set_analysis('wave')
# ui.ignore(None, 21.4)
# ui.ignore(21.7, None)
# ui.notice(21.4, 21.7)

ui.set_analysis('energy')
ui.notice(0.5712, 0.5795)

line = ui.gauss1d(name='line')

# line.fwhm = 0.00001
# line.pos = 21.6
line.fwhm = 0.00001
line.pos = d10._hc / 21.6

line.fwhm.frozen = True
line.pos.frozen = True

ui.set_source(10, line)
ui.group_width(10, 2)
ui.set_stat("cstat")

s0 = ui.calc_stat()
ui.fit(10)
fr = ui.get_fit_results()
s1 = ui.calc_stat()

print("\n")
print("*** {:.7e}".format(s0))
print("*** {:.7e}".format(s1))
print("*** {:.7e}".format(fr.statval))

print("*** niter = {}".format(fr.nfev))
```

which outputs

```
Dataset               = 10
Method                = levmar
Statistic             = cstat
Initial fit statistic = 42.8273
Final fit statistic   = 2.26955 at function evaluation 11
Data points           = 32
Degrees of freedom    = 31
Probability [Q-value] = 1
Reduced statistic     = 0.0732112
Change in statistic   = 40.5578
   line.ampl      19.6276      +/- 6.25513
WARNING: data set 10 has associated backgrounds, but they have not been subtracted, nor have background models been set


*** 4.2827348e+01
*** 2.2695476e+00
*** 2.2695476e+00
*** niter = 11
```

So this fit has done more than 2 iterations and the `calc_stat` output matches the fit results. Our test suite is lacking in analysis=wave tests, so it is less surprising to me that this wasn't caught. I have some hand-wavey thoughts on what the problem was, but haven't tracked them down. I think I have enough to get a sensible test written.

**Closed** 2020-03-18 19:23 UTC
