### ISSUE TITLE
More oddities in Travis tests: build 3 tests now failing for numerical tolerances

### ISSUE THREAD

**Issue by DougBurke** [sherpa/sherpa#566] opened 2018-12-02 15:30 UTC
PRs that @dtnguyen2 and I have made this week-end are both failing for "build 3" on Travis, with the output below. The code we have written (eg in #562 I only added tests, not code) is not related to these tests, and we can see that it appears to be a tolerance issue.

However, it only appears to be this run - other runs don't show the issue. I know that the XSPEC models in this version can over-write memory, so maybe there's some bizarre thing going on there. Or it's some other part of the system that has changed. One option is to remove this build, as we don't really support XSPEC 12.9.0 anymore.

```
================================== FAILURES ===================================
___________________________ test_threads.test_histo ____________________________
self = <test_astro.test_threads testMethod=test_histo>
    @requires_fits
    def test_histo(self):
        self.run_thread('histo')
        assert ui.get_fit_results().statval == approx(14.7264, rel=1e-4)
        assert self.locals['g1'].fwhm.val == approx(0.0232473, rel=1e-4)
        assert self.locals['g1'].pos.val == approx(1.26713, rel=1e-4)
>       assert self.locals['g1'].ampl.val == approx(40.4503, rel=1e-4)
E       AssertionError: assert 40.4514347531601 == 40.4503 +- 4.0e-03
E        +  where 40.4514347531601 = <Parameter 'ampl' of model 'g1'>.val
E        +    where <Parameter 'ampl' of model 'g1'> = <Gauss1D model instance 'g1'>.ampl
E        +  and   40.4503 +- 4.0e-03 = approx(40.4503, rel=0.0001)
sherpa/astro/tests/test_astro.py:418: AssertionError
----------------------------- Captured stdout call -----------------------------
 Solar Abundance Vector set to angr:  Anders E. & Grevesse N. Geochimica et Cosmochimica Acta 53, 197 (1989)
 Cross Section Table set to bcmc:  Balucinska-Church and McCammon, 1998
___________________________ test_threads.test_pileup ___________________________
self = <test_astro.test_threads testMethod=test_pileup>
    @requires_fits
    @requires_xspec
    def test_pileup(self):
        self.run_thread('pileup')
    
        fr = ui.get_fit_results()
        covarerr = sqrt(fr.extra_output['covar'].diagonal())
>       assert covarerr[0] == approx(684.056 , rel=1e-4)
E       AssertionError: assert 684.0561045288689 == 684.056 +- 6.8e-02
E        +  where 684.056 +- 6.8e-02 = approx(684.056, rel=0.0001)
sherpa/astro/tests/test_astro.py:219: AssertionError
----------------------------- Captured stdout call -----------------------------
 Solar Abundance Vector set to angr:  Anders E. & Grevesse N. Geochimica et Cosmochimica Acta 53, 197 (1989)
 Cross Section Table set to bcmc:  Balucinska-Church and McCammon, 1998
__________________________ test_threads.test_spatial ___________________________
self = <test_astro.test_threads testMethod=test_spatial>
    @requires_fits
    def test_spatial(self):
        self.run_thread('spatial')
        self.assertEqualWithinTol(ui.get_fit_results().statval,
                                  -59229.749441, 1e-4)
        assert self.locals['g1'].fwhm.val == approx(61.5615, rel=1e-4)
>       assert self.locals['g1'].xpos.val == approx(4070.45, rel=1e-4)
E       AssertionError: assert 4070.4512481717043 == 4070.45 +- 4.1e-01
E        +  where 4070.4512481717043 = <Parameter 'xpos' of model 'g1'>.val
E        +    where <Parameter 'xpos' of model 'g1'> = <Gauss2D model instance 'g1'>.xpos
E        +  and   4070.45 +- 4.1e-01 = approx(4070.45, rel=0.0001)
sherpa/astro/tests/test_astro.py:201: AssertionError
```

**Comment by dtnguyen2** [comment] 2018-12-02 16:01
LevMarDif correctly detects that 'improper input parameters' (info == 0).  So the code that I have added is outside of lmdif.  I have not made any changes to lmdif so I suspect that this is an Xspec issue

**Comment by olaurino** [comment] 2018-12-03 13:58
I triggered a travis run on the latest master commit on my fork. If it fails it's something environmental, if it doesn't fail it's a regression. While indeed we can and should remove the 12.9.0 job in favor of 12.10.0 (will I ever get to that) it's useful to know why we are seeing a sudden change.

**Comment by olaurino** [comment] 2018-12-03 14:22
As shown in https://travis-ci.org/olaurino/sherpa/jobs/462814929 the current master branch would fail in Travis, so as we suspected something has changed in the environment that makes those tests fail with xspec 12.9.0. I can't possibly look into it now, but there must be a difference (e.g. version of numpy or something like that) that explains the failure and that it would be good to understand even if we don't act on it.

**Comment by olaurino** [comment] 2018-12-03 14:32
Just so I remember, there are actually a number of 12.9.0 jobs currently in Travis, and the only one that fails is the python 2.7 one. I am guessing it's not a coincidence, as that's the only difference w.r.t the others. For now I'll update the tests so they all use 12.9.1, but we need the 12.10.0 job asap (I still need to build xspec 12.10.0 as a conda package on both linux and macOS, ugh).

**Comment by olaurino** [comment] 2018-12-03 14:33
Btw it could well be that the 2.7 job will fail with 12.9.1 as well. We have to decide what to do in that case.

**Comment by olaurino** [comment] 2018-12-03 14:47
We do now, let's see how it goes, but let's start thinking what to do if it fails. Although it's not a CIAO issue, so for what CIAO is concerned I'd just get the #564 merged before we figure out the xspec 12.9.0+Python 2.7 issue, if you agree.

**Comment by DougBurke** [comment] 2018-12-03 14:51
I agree that **for now** we should just remove problematic build from Travis, and worry about its cause later.

**Comment by olaurino** [comment] 2019-01-18 22:57
I'm trying to figure this out, and it's kind of hard. Here is the diff between jobs
https://travis-ci.org/sherpa/sherpa/jobs/462329764 (which failed)

and 

https://travis-ci.org/sherpa/sherpa/jobs/461842788 (which passed)

```` diff
1c1
<     astropy:                2.0.9-py27hdd07704_1                   
---
>     astropy:                2.0.9-py27hdd07704_0                   
47a48
>     pathlib2:               2.3.2-py27_0                           
51c52
<     pluggy:                 0.6.0-py27_0                           
---
>     pluggy:                 0.8.0-py27_0                           
56c57
<     pytest:                 3.6.4-py27_0                           
---
>     pytest:                 4.0.0-py27_0                           
61a63
>     scandir:                1.9.0-py27h14c3975_0  
````

Not sure what to make of it but I'll keep looking.

**Comment by DougBurke** [comment] 2019-01-26 19:31
I am not convinced it's worth spending much more time on this.

**Comment by olaurino** [comment] 2019-02-01 03:18
I remember adding a comment re whether we should keep supporting XSPEC and Python 2.7, but I can't seem to find it. So, here it is again: either we fix this issue with XSPEC and Python 2.7 or we claim that we drop direct XSPEC support for Python 2.7. Since there is a regression with only one test it means that users should still be able to build Sherpa against XSPEC in 2.7, but since we haven't tracked down the issue it's hard to document this meaningfully. @DougBurke what do you think?

**Comment by DougBurke** [comment] 2019-02-01 12:16
I have been advocating dropping python 2.7 support completely ...

Doug

**Comment by olaurino** [comment] 2019-02-01 13:42
Ok, so I'll simply drop the xspec/2.7 job. Thanks.

[According to conda](https://anaconda.org/sherpa/sherpa/files?version=4.10.2) we still have plenty of 2.7 downloads. I assume many downloads come from downstream projects and their continuous integration. However I am not aware of any such projects supporting python 2.7. Unless I am missing some of our own tests downloading sherpa for python 2.7 from `anaconda.org` we can't say where such downloads are coming from. (Note [PyPI](https://pypistats.org/packages/sherpa) tells a different story.)

Maybe we should deprecate python 2.7 and remove it in one of our very next releases?

**Comment by anetasie** [comment] 2019-02-06 11:28
Yes, we should deprecate python 2.7.

**Closed** 2019-02-08 00:09 UTC
Labels: area:tests
