### ISSUE TITLE
ui.fake_pha does not work with input list of length 1

### ISSUE THREAD

**Issue by hamogu** [sherpa/sherpa#1722] opened 2023-03-04 23:28 UTC
`sherpa.astro.ui.fake_pha` can take an individual ARF and RMF as input, or a list of ARF's and RMFs. The latter is important in particular for Chandra/HETGS because the HRC detector does not do order-sorting, and thus more than one spectral order contributes to the observed signal.

Curiously though, it fails if the list of ARFs and RMFs has only one element in it. Note to reproduce: The example below uses OBSID 26222 downloaded directly from the archive, but that's just an example, the bug is not due to the specific OBSID.

```Python
from sherpa.astro import ui
for id in ['singleinput', 'list', 'list_one_element']:
    ui.set_source(id, ui.xsapec.a1)
ui.fake_pha('singleinput', 
            '26222/primary/responses/hrcf26222N001_Lm1_arf2.fits.gz',
            '26222/primary/responses/hrcf26222N001_Lm1_rmf2.fits.gz',
           1e4)
ui.fake_pha('list', 
            ['26222/primary/responses/hrcf26222N001_Lm1_arf2.fits.gz',
             '26222/primary/responses/hrcf26222N001_Lm2_arf2.fits.gz'],
            ['26222/primary/responses/hrcf26222N001_Lm1_rmf2.fits.gz',
             '26222/primary/responses/hrcf26222N001_Lm2_rmf2.fits.gz'],
           1e4)
ui.fake_pha('list_one_element', 
            ['26222/primary/responses/hrcf26222N001_Lm1_arf2.fits.gz'],
            ['26222/primary/responses/hrcf26222N001_Lm1_rmf2.fits.gz'],
           1e4)
```

The first two fakes work, but the last one gives:
```Python
---------------------------------------------------------------------------
DataErr                                   Traceback (most recent call last)
Cell In[8], line 1
----> 1 ui.fake_pha('list_one_element', 
      2             ['26222/primary/responses/hrcf26222N001_Lm1_arf2.fits.gz'],
      3             ['26222/primary/responses/hrcf26222N001_Lm1_rmf2.fits.gz'],
      4            1e4)

File <string>:1, in fake_pha(id, arf, rmf, exposure, backscal, areascal, grouping, grouped, quality, bkg)

File ~/mambaforge/envs/ciao-4.15/lib/python3.10/site-packages/sherpa/astro/ui/utils.py:8972, in Session.fake_pha(self, id, arf, rmf, exposure, backscal, areascal, grouping, grouped, quality, bkg)
   8968         self.set_bkg(id, bkg)
   8970 # Calculate the source model, and take a Poisson draw based on
   8971 # the source model.  That becomes the simulated data.
-> 8972 m = self.get_model(id)
   8974 fake.fake_pha(d, m, is_source=False, add_bkgs=bkg is not None,
   8975               id=str(id), bkg_models=bkg_models)
   8976 d.name = 'faked'

File ~/mambaforge/envs/ciao-4.15/lib/python3.10/site-packages/sherpa/ui/utils.py:6359, in Session.get_model(self, id)
   6357 data = self.get_data(id)
   6358 model, is_source = self._get_model_status(id)
-> 6359 return self._add_convolution_models(id, data, model, is_source)

File ~/mambaforge/envs/ciao-4.15/lib/python3.10/site-packages/sherpa/astro/ui/utils.py:9137, in Session._add_convolution_models(self, id, data, model, is_source)
   9134 if not isinstance(data, sherpa.astro.data.DataPHA) or not is_source:
   9135     return model
-> 9137 return sherpa.astro.background.add_response(self, id, data, model)

File ~/mambaforge/envs/ciao-4.15/lib/python3.10/site-packages/sherpa/astro/background.py:73, in add_response(session, id, data, model)
     71 pileup_model = session._pileup_models.get(id)
     72 bkg_srcs = session._background_sources.get(id, {})
---> 73 return get_response_for_pha(data, model, bkg_srcs, pileup_model, id)

File ~/mambaforge/envs/ciao-4.15/lib/python3.10/site-packages/sherpa/astro/background.py:115, in get_response_for_pha(data, model, bkg_srcs, pileup_model, id)
    112 if id is None:
    113     id = data.name
--> 115 resp = data.get_full_response(pileup_model)
    116 if data.subtracted or (len(bkg_srcs) == 0):
    117     return resp(model)

File ~/mambaforge/envs/ciao-4.15/lib/python3.10/site-packages/sherpa/astro/data.py:2403, in DataPHA.get_full_response(self, pileup_model)
   2400 if len(self._responses) > 1:
   2401     return instrument.MultipleResponse1D(self)
-> 2403 return instrument.Response1D(self)

File ~/mambaforge/envs/ciao-4.15/lib/python3.10/site-packages/sherpa/astro/instrument.py:784, in Response1D.__init__(self, pha)
    782 arf, rmf = pha.get_response()
    783 if arf is None and rmf is None:
--> 784     raise DataErr('norsp', pha.name)
    786 NoNewAttributesAfterInit.__init__(self)

DataErr: No instrument response found for dataset 
```

**Comment by DougBurke** [comment] 2023-03-05 03:49
I've started work on the fake_pha code in #1684 - it started out as a doc change but quickly grew. I'll add this to the list of things to look at there. I haven't looked at the ode for a little while so I'm not sure of the state of that PR (other than I've marked it as a draft so I had planned to get back to it).

**Comment by DougBurke** [comment] 2023-03-08 20:30
My bet is that the problem is in

https://github.com/sherpa/sherpa/blob/5bde128a691551df3f6817431f257ea9746c8d35/sherpa/astro/ui/utils.py#L8974-L8977

where we use `range(len(arf))`. This will use, in this case, `[0]`. Unfortunately the default id is `1` which is what the `pha.get_response()` line uses, and as there is no `resp_id=1` we get `None,None` back and hence the error.

Which suggests there's an easy fix and a much-more-extensive-and-invasive fix (which will probably still need the easy fix).

**Closed** 2023-04-06 19:18 UTC
Labels: type:bug, area:code, note:can-workaround
