### ISSUE TITLE
load_pha segfault

### ISSUE THREAD

**Issue by JohannesBuchner** [sherpa/sherpa#817] opened 2020-05-26 15:04 UTC
Hi all,

I am getting a segmentation fault when loading this file with load_pha: http://www.mpe.mpg.de/~jbuchner/temp/foo.fits

```
[user:/tmp] $ ciao 
CIAO configuration is complete... 
CIAO 4.12 Monday, November 25, 2019
  bindir      : /home/user/bin/ciao-4.12/bin
  CALDB       : 4.9.0
[user:/tmp] $ which python3
/home/user/bin/ciao-4.12/ots/bin/python3
[user:/tmp] $ python3 -c 'from sherpa.astro.ui import load_pha; load_pha("foo.fits")'
Segmentation fault (core dumped)
```

I nulled all the COUNTS on purpose, but it also happens otherwise.

Please let me know what is wrong with the file, and hopefully repair sherpa to handle this more gracefully. It loads fine in threeML and xspec.

**Comment by anetasie** [comment] 2020-05-26 22:07
Thanks. I get a Seg.Fault with a standard CIAO DM tools. dmlist. I'll send this to our system group.

```
$ dmlist foo.fits header |more
# 24849: 	 Received error signal SIGSEGV-segmentation violation.
# 24849: 	 An invalid memory reference was made.
# 24849:		 segmentation fault: DMLIST (1) is: exit_upon_error->NULL
```

**Comment by hamogu** [comment] 2020-05-27 14:48
Sherpa does have an alternative io backend that can be used for file access.

You can set the `io_pkg` in your `.sherpa.rc` file to `pyfits` (the relevant astropy module):
https://cxc.cfa.harvard.edu/sherpa/ahelp/sherparc.html
Obviously, that means that stropy has to be installed in your ciao environment but that is relatively simple. Just activate your CIAO environment and type `pip install astropy`. Using the pyfits backend, I can read your file into sherpa.

I agree that this seg fault needs to be fixed, but in the meantime, using astropy to read the files might solve your problem.

**Comment by anetasie** [comment] 2020-05-27 14:51
Here is a bit more details from our help system:

> This looks to be a problem with the DSTYPE keyword in the file
% fold foo.fits | grep DSTYP
DSTYPE  = 'SourceSpec'         / Dataset type: EventFile, Image, etc.    
The DM "reserves" the DSTYPE keywords to store subspace(?) information.  It shouldn't crash here ... I'd expect it to just ignore it since it doesn't know what to do with it.
>
> You can use ftools to delete the keyword
% fthedit foo.fits dstype delete
(all DM tools, including dmhedit just crash).

> Note:  fverify also does warn about a missing long-string (LONGSTR) keyword
% fverify foo.fits
*** Warning: The OGIP long string keyword convention is used without the
             recommended LONGSTRN keyword.  (HEASARC Convention)
but that doesn't seem to cause any actual problems.

I tried to change the backend to read the file using the 'pyfits' option  and it worked fine.

**Comment by DougBurke** [comment] 2020-09-09 15:45
I've confirmed that this file can now be read in with Crates using the CIAO 4.13 development branch.

**Comment by hamogu** [comment] 2021-01-07 13:35
Closing since this seems to work on 4.13

**Closed by hamogu** 2021-01-07 13:35 UTC
Labels: type:bug
