### ISSUE TITLE
double print out after fit

### ISSUE THREAD

**Issue by anetasie** [sherpa/sherpa#519] opened 2018-10-12 14:29 UTC
I get double print out after ```fit()``` in 4.10.1 release build from source in anaconda/python2.7 on MAC 10.11.6. This is regardless of whether I use 1 or 2 or more data sets.

```
In [16]: fit()
Datasets              = 1, 2
Method                = neldermead
Statistic             = chi2xspecvar
Initial fit statistic = 3.02974e+09
Final fit statistic   = 414.44 at function evaluation 310
Data points           = 410
Degrees of freedom    = 408
Probability [Q-value] = 0.40223
Reduced statistic     = 1.01578
Change in statistic   = 3.02974e+09
   p1.gamma       0.657635    
   p1.ampl        0.000460297 
INFO:sherpa.astro.ui.utils:Datasets              = 1, 2
Method                = neldermead
Statistic             = chi2xspecvar
Initial fit statistic = 3.02974e+09
Final fit statistic   = 414.44 at function evaluation 310
Data points           = 410
Degrees of freedom    = 408
Probability [Q-value] = 0.40223
Reduced statistic     = 1.01578
Change in statistic   = 3.02974e+09
   p1.gamma       0.657635    
   p1.ampl        0.000460297 
```

**Comment by olaurino** [comment] 2018-10-12 14:35
I can't reproduce this issue in a simple fit. Could you provide more information? e.g. the previous 15 commands?

**Comment by anetasie** [comment] 2018-10-12 14:41
I copied the data files to /pool14/aneta.
Here are the commands:

''''
from sherpa.astro.ui import *
set_method('neldermead')
set_stat('chi2xspecvar')

load_pha("spec1_rgs1_snr3.fits")
load_bkg("bgd1_rgs1_new.fits")
load_rmf("rgs1_new.rsp")

load_pha(2,"spec1_rgs2_snr3.fits")
load_bkg(2,"bgd1_rgs2_new.fits")
load_rmf(2,"rgs2_new.rsp")
import matplotlib
%matplotlib
plot_data()
calc_data_sum(id=2)
subtract()
subtract(2)
set_model(powlaw1d.p1)
set_model(2,p1)
calc_data_sum(id=2)
fit()
fit(1)
plot_fit(1)
plot_fit(2)
'''

**Comment by anetasie** [comment] 2018-10-12 14:42
This is in python 2.7:
```
Python 2.7.15 |Anaconda custom (x86_64)| (default, May  1 2018, 18:37:05) 
Type "copyright", "credits" or "license" for more information.

IPython 5.1.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

```

**Comment by anetasie** [comment] 2018-10-12 14:46
ok this printout was in the old version of sherpa. I did use ```python setup.py install```and assumed that the installation will be in my default anaconda, but it looks like the import gives a very old version of sherpa:

```
In [2]: sherpa.__version__
Out[2]: '4.8.2'
```

So is there another step after install to actually have an updated version in the anaconda system?

**Comment by olaurino** [comment] 2018-10-12 14:53
No, no additional step. It could be that you installed multiple versions via multiple avenues, e.g. `conda install` and `python setup.py install`. Try figuring out what's going on in your environment by reading the output of this command:
```
python -c "import sherpa; print(sherpa.__file__)"
```

That should give you an idea of whether the additional installation is in the environment you activated, or there's something even messier going on (e.g. `PYTHONPATH` and the like).

Once you can confirm you installed sherpa twice you can follow the instructions we give users in the README, i.e.:

> NOTE: if you run both install and develop or test in the same Python environment you end up with two competing installations of Sherpa which result in unexpected behavior. If this happens, simply run pip uninstall sherpa as many times as necessary, until you get an error message that no more Sherpa installations are available. At this point you can re-install Sherpa.
> ** The same issue may occur if you install the Sherpa binary release and then try to build Sherpa from source in the same environment.**

I am going to close this ticket, but if you still have issues please feel free to keep posting in this thread.

**Closed by olaurino** 2018-10-12 14:53 UTC

**Comment by anetasie** [comment] 2018-10-12 14:54
If I'm in the install directory I can see the correct version, but I cannot do ```import```

Anetas-iMac:sherpa aneta$ python -c "import sherpa; print(sherpa._version.get_versions())"
{'version': '4.10.1', 'full': 'a252b75f226362511f7d251e96e190b7ffc4067e'}
Anetas-iMac:sherpa aneta$ ipython
Python 2.7.15 |Anaconda custom (x86_64)| (default, May  1 2018, 18:37:05) 
Type "copyright", "credits" or "license" for more information.

IPython 5.1.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: from sherpa.astro.ui import *
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-2101421ec4a2> in <module>()
----> 1 from sherpa.astro.ui import *

/Users/aneta/Software/SherpaStandalone/sherpa/sherpa/astro/ui/__init__.py in <module>()
     18 #
     19 
---> 20 import sherpa.all
     21 import sherpa.astro.all
     22 import sherpa.astro.ui.utils

/Users/aneta/Software/SherpaStandalone/sherpa/sherpa/all.py in <module>()
     33 warning = logging.getLogger(__name__).warning
     34 
---> 35 from sherpa.data import *
     36 from sherpa.estmethods import *
     37 from sherpa.fit import *

/Users/aneta/Software/SherpaStandalone/sherpa/sherpa/data.py in <module>()
     28 import numpy
     29 
---> 30 from sherpa.models.regrid import EvaluationSpace1D
     31 from sherpa.utils.err import DataErr, NotImplementedErr
     32 from sherpa.utils import SherpaFloat, NoNewAttributesAfterInit, \

/Users/aneta/Software/SherpaStandalone/sherpa/sherpa/models/__init__.py in <module>()
     18 #
     19 
---> 20 from sherpa.models.parameter import *
     21 from sherpa.models.model import *
     22 from sherpa.models.basic import *

/Users/aneta/Software/SherpaStandalone/sherpa/sherpa/models/parameter.py in <module>()
     23 import logging
     24 import numpy
---> 25 from sherpa.utils import SherpaFloat, NoNewAttributesAfterInit
     26 from sherpa.utils.err import ParameterErr
     27 

/Users/aneta/Software/SherpaStandalone/sherpa/sherpa/utils/__init__.py in <module>()
     37 # Note: _utils.gsl_fcmp and _utils.ndtri are not exported from
     38 #       this module; is this intentional?
---> 39 from sherpa.utils._utils import hist1d, hist2d
     40 from sherpa.utils import _utils
     41 

ImportError: No module named _utils

**Comment by olaurino** [comment] 2018-10-12 14:56
You should never run sherpa from the source folder unless you are in development mode (see README, `python setup.py develop`). So it's not surprising it's not working. Try what I suggested in the previous comment, but there might be something else going wrong in your environment.

**Comment by anetasie** [comment] 2018-10-12 14:58
I guess I'm confused. I did not install a new version on this computer, so this is the first installation from source. I followed the steps from your email:

```
$ git clone https://github.com/sherpa/sherpa
$ cd sherpa
$ git checkout 4.10.1
$ python setup.py install
```
If I change the directory, than the version that I get is old one 4.8.2, while I don't get the new one.

**Comment by anetasie** [comment] 2018-10-12 14:59
This is from the other directory, not the install one:

```
python -c "import sherpa; print(sherpa._version.get_versions())"
{'version': '4.8.2', 'full': '93834846f02bfcf1106c8f753f0bdbb8af7ae0a7'}

```

**Comment by olaurino** [comment] 2018-10-12 15:05
Could you please provide the output of

```
python -c "import sherpa; print(sherpa.__file__)"
````

**Comment by anetasie** [comment] 2018-10-12 15:07
Install directory:
``` 
pwd
/Users/aneta/Software/SherpaStandalone/sherpa
Anetas-iMac:sherpa aneta$ python -c "import sherpa; print(sherpa.__file__)"
sherpa/__init__.pyc
```

other directory

```
Anetas-iMac:~ aneta$ python -c "import sherpa; print(sherpa.__file__)"
/Users/aneta/anaconda/anaconda/lib/python2.7/site-packages/sherpa/__init__.pyc
```

**Comment by olaurino** [comment] 2018-10-12 15:08
Please don't run anything from the source code directory, that's not supposed to work unless you are in development mode.

Could you please provide the output of:
```
ls /Users/aneta/anaconda/anaconda/lib/python2.7/site-packages/
```

**Comment by anetasie** [comment] 2018-10-12 15:11
here are relevant lines
```
....
setuptools.pth
sherpa
sherpa-4.10.1-py2.7-macosx-10.6-x86_64.egg
sherpa-4.8.2-py2.7.egg-info
simplegeneric-0.8.1-py2.7.egg-info
simplegeneric.py
.....
```

**Comment by olaurino** [comment] 2018-10-12 15:12
As I mentioned initially, you have two versions of sherpa installed. Please use `pip` to remove them both:
```
pip uninstall sherpa
pip uninstall sherpa
pip uninstall sherpa
```

The last command should give you an error, that's good.

Then go back to the source code folder, type:

```
python setup.py install
```
Move to a different folder, now the version will be the correct one.

**Comment by anetasie** [comment] 2018-10-12 15:14
ok I know I had two version installed, but there was nothing about uninstall in the instruction.
Why the 'sherpa' was not updated with a new versioin?
I suggest to add the 'uninstall' to the README.

**Comment by anetasie** [comment] 2018-10-12 15:15
Here are my install dates:

drwxr-xr-x   35 aneta  staff    1190 Jan 26  2017 sherpa
drwxr-xr-x    6 aneta  staff     204 Oct 12 09:58 sherpa-4.10.1-py2.7-macosx-10.6-x86_64.egg
drwxr-xr-x    8 aneta  staff     272 Oct 25  2016 sherpa-4.8.2-py2.7.egg-info

**Comment by olaurino** [comment] 2018-10-12 15:40
Since we are in standalone world, where the user is the generic Python user, the user should be aware of the intricacies of the python installation process (well, all the possible Python installation processes). I just tried to install astropy v2.0.8, then astropy v1.3.3, I ended up with two installations, I wasn't informed I was downgrading, I wasn't asked if I was sure about what I was doing, whether I wanted to keep the old files, which were kept. Yet there is nothing in the astropy documentation that mentions uninstall (http://docs.astropy.org/en/stable/install.html). That's just the way `python setup.py install` works. Conda works differently, `pip` also works differently. Not to mention packages in the OS package manager(s) (yum, apt, homebrew, macports, chocolatey, etc.) So it really depends on a lot of variables that have to do with the user's environment and preferences.

The README shows how to recover from a state where you have multiple installations of Sherpa, which goes already above and beyond what a generic Python package will tell you about these weird cases.

To be fair, in this specific case Sherpa 4.8.2 used a different `install` command than `4.10.1` does. In general I think `python setup.py install` doesn't care too much about what you are doing and will keep multiple versions installed at the same time, but you will most likely get the latest one you installed. Which is something I never trust, I had subtle issues in the past for this reason. So in your very specific case (`python setup.py install`, existing 4.8.2 version updating to 4.10.1) the result was particularly surprising as Python was still picking the old version over the new. But that's on Python having an incredibly complicated, redundant, and unreliable installation process, not on Sherpa.

**Comment by anetasie** [comment] 2018-10-12 15:50
I still have an issue - now with 2 data sets in ```fit()```  or ```fit(1,2) uses only one data set to fit,

```
In [16]: sherpa.__version__
Out[16]: '4.10.1-py2.7-macosx-10.6-x86_64.egg'

In [13]: fit()
Dataset               = 1
Method                = neldermead
Statistic             = chi2xspecvar
Initial fit statistic = 194.27
Final fit statistic   = 194.27 at function evaluation 288
Data points           = 204
Degrees of freedom    = 202
Probability [Q-value] = 0.639199
Reduced statistic     = 0.961732
Change in statistic   = 0
   p1.gamma       0.563057    
   p1.ampl        0.00047677  

In [19]: list_data_ids()
Out[19]: [1, 2]

In [20]: fit(1,2)
Dataset               = 1
Method                = neldermead
Statistic             = chi2xspecvar
Initial fit statistic = 194.27
Final fit statistic   = 194.27 at function evaluation 288
Data points           = 204
Degrees of freedom    = 202
Probability [Q-value] = 0.639199
Reduced statistic     = 0.961732
Change in statistic   = 0
   p1.gamma       0.563057    
   p1.ampl        0.00047677  
```

**Comment by anetasie** [comment] 2018-10-12 15:55
ok. I only set the model for data id=1, so this is expected that only one data set is fit!

**Comment by anetasie** [comment] 2018-10-12 15:57
Thanks for the comments on installation. I expected to have both version installed and python to pick up the most recent one. This is why I was confused with the install. Anyway, if we have another user with the similar issue we can figure out what type of information we add to our docs.

**Comment by olaurino** [comment] 2018-10-12 16:10
Note that that shouldn't happen with more recent versions of Sherpa. I.e. I expect that if you had 4.10.0 installed and you just `python setup.py install` 4.10.1 the Python gods would let you import from 4.10.1. The problem is that at some point along the way we changed the `install` command internals to extend a different (more proper) upstream command, so 4.8.2 and 4.10 install Sherpa using different Python mechanisms, and the Python installation infrastructure mess did the rest.
